࿓❯ Update
Signed-off-by: Victor-ray, S <12261439+ZendaiOwl@users.noreply.github.com>

diff --git a/bin/ncp-update b/bin/ncp-update
--- a/bin/ncp-update
+++ b/bin/ncp-update
@@ -44,12 +44,8 @@ function log
 
 function remove_tmp_directory
 {
-  if ! rm --recursive --force "$TMPDIR"; then
-    log 2 "Failed to remove directory: $TMPDIR"
-    return 1
-  else
-    log 0 "Removed tmp directory: $TMPDIR"
-    return 0
+  if ! rm --recursive --force "$TMPDIR"; then log 2 "Failed to remove directory: $TMPDIR"; return 1
+  else log 0 "Removed tmp directory: $TMPDIR"; return 0
   fi
 }
 
@@ -58,20 +54,17 @@ function clean_ncp_update
   if ! cd /; then
     log 2 "Failed to change directory to: /"
     log -1 "Attempting to remove tmp directory nonetheless"
-    if ! remove_tmp_directory; then
-      exit 1
+    if ! remove_tmp_directory; then exit 1
     fi
   else
-    if ! remove_tmp_directory; then
-      exit 1
+    if ! remove_tmp_directory; then exit 1
     fi
   fi
 }
 
 [[ -z "$DBG" ]] || set -"$DBG"
 
-if [[ -f /.dockerenv ]] || [[ -f /.docker-image ]] || [[ "$DOCKERBUILD" == 1 ]]
-then
+if [[ -f /.dockerenv ]] || [[ -f /.docker-image ]] || [[ "$DOCKERBUILD" == 1 ]]; then
   log 1 "Docker images should be updated by replacing the container from the latest docker image.
 Refer to the documentation for instructions: https://docs.nextcloudpi.com
 If you are sure that you know what you are doing, you can still execute the update script by running it like this:
@@ -80,9 +73,7 @@ If you are sure that you know what you are doing, you can still execute the upda
 fi
 
 {
-  if [[ "$(id -u)" -ne 0 ]]; then
-    log 2 "Must be run as root or with sudo. Try 'sudo ${BASH_SOURCE[0]}'"
-    exit 1
+  if [[ "$(id -u)" -ne 0 ]]; then log 2 "Must be run as root or with sudo. Try 'sudo ${BASH_SOURCE[0]}'"; exit 1
   fi
 
   #OWNER="${OWNER:-nextcloud}"
@@ -96,22 +87,18 @@ fi
 
   log -1 "Downloading updates"
   git clone --depth 20 -b "$BRANCH" -q https://github.com/"$OWNER"/"$REPO".git "$TMPDIR" || {
-    log 2 "No internet connectivity"
-    exit 1
+    log 2 "No internet connectivity"; exit 1
   }
 
   # shellcheck disable=SC2164
   [[ -f /.ncp-image ]] || {
     # Update locally during build
-    if ! cd "$TMPDIR"; then
-      log 2 "Failed to change directory to: $TMPDIR"
-      exit 1
+    if ! cd "$TMPDIR"; then log 2 "Failed to change directory to: $TMPDIR"; exit 1
     fi
 
     [[ -z "$2" ]] || {
       git fetch origin "$2" || {
-        log 2 "Could not fetch: $2"
-        exit 1
+        log 2 "Could not fetch: $2"; exit 1
       }
       git checkout FETCH_HEAD
     }
@@ -149,7 +136,6 @@ fi
     sed '/HEAD ->\|origin/s|\[.*\(tag: v[0-9]\+\.[0-9]\+\.[0-9]\+\).*\]|[\1]|' | \
     sed 's|* \[tag: |[|' > /usr/local/etc/ncp-changelog
 
-  log 0 "NextcloudPi updated to: $VER"
-  exit 0
+  log 0 "NextcloudPi updated to: $VER"; exit 0
 
 } # force to read the whole thing into memory, as its contents might change in update.sh
diff --git a/bin/ncp-update-nc b/bin/ncp-update-nc
--- a/bin/ncp-update-nc
+++ b/bin/ncp-update-nc
@@ -274,25 +274,18 @@ function hasText
 VER="$1"
 BIN="${0##*/}"
 
-if isFile '/usr/local/etc/library.sh'; then
-  # shellcheck disable=SC1090
-  source '/usr/local/etc/library.sh'
-elif isFile 'etc/library.sh'; then
-  # shellcheck disable=SC1090
-  source '/usr/local/etc/library.sh'
+# shellcheck disable=SC1090
+if isFile '/usr/local/etc/library.sh'; then source '/usr/local/etc/library.sh'
+elif isFile 'etc/library.sh'; then source '/usr/local/etc/library.sh'
 fi
 
 # pre-checks
 ####################
-if isZero "$VER"; then
-  log 2 "Usage: $BIN <version>"
-  exit 1
+if isZero "$VER"; then log 2 "Usage: $BIN <version>"; exit 1
 fi
 
-if isFile '/.docker-image'; then
-  BASEDIR='/data'
-else
-  BASEDIR='/var/www'
+if isFile '/.docker-image'; then BASEDIR='/data'
+else BASEDIR='/var/www'
 fi
 
 log -2 "BASEDIR: $BASEDIR"
@@ -311,23 +304,19 @@ ncc status &>/dev/null          || { [[ "$DBG" == x ]] && ncc status; echo "Next
 # check version
 ####################
 
-if isRoot; then
-  SUDO=(sudo -u www-data)
+if isRoot; then SUDO=(sudo -u www-data)
 fi
 
 CURRENT="$( "${SUDO[@]}" php /var/www/nextcloud/occ status | grep "version:" | awk '{ print $3 }' )"
-
 MAJOR_CUR="$( cut -d. -f1 <<<"$CURRENT" )"
 MAJOR_NEW="$( cut -d. -f1 <<<"$VER" )"
+
 if [[ "$((MAJOR_NEW - MAJOR_CUR))" -gt 1 ]]; then
-  log 2 "Upgrade cannot skip major versions. Please upgrade one major version at a time" >&2
-  exit 1
+  log 2 "Upgrade cannot skip major versions. Please upgrade one major version at a time" >&2; exit 1
 fi
 
-if [[ "$MAJOR_NEW" -ge 24 ]] && [[ "$(lsb_release -r)" =~ .*10 ]]
-then
-  log 2 "NCP doesn't support Nextcloud versions greater than 23 with Debian 10 (Buster). Please run ncp-dist-upgrade."
-  exit 1
+if [[ "$MAJOR_NEW" -ge 24 ]] && [[ "$(lsb_release -r)" =~ .*10 ]]; then
+  log 2 "NCP doesn't support Nextcloud versions greater than 23 with Debian 10 (Buster). Please run ncp-dist-upgrade."; exit 1
 fi
 
 grep -qP "\d+\.\d+\.\d+" <<<"$CURRENT" || { echo "Malformed version $CURRENT"; exit 1; }
@@ -338,10 +327,8 @@ log -1 "Available Nextcloud version: $VER"
 is_more_recent_than "$VER" "$CURRENT" || { log -1 "Nothing to update"; exit 1; } # we want `exit 1` so the autoupdate doesn't notify success in this case
 
 
-if ! is_more_recent_than '25.0.0' "$VER" && is_more_recent_than "8.1.0" "${PHPVER}.0" && is_docker
-then
-  echo 'You need to upgrade to a later docker image in order to upgrade to Nextcloud 25+'
-  exit 1
+if ! is_more_recent_than '25.0.0' "$VER" && is_more_recent_than "8.1.0" "${PHPVER}.0" && is_docker; then
+  echo 'You need to upgrade to a later docker image in order to upgrade to Nextcloud 25+'; exit 1
 fi
 
 # make sure that cron.php is not running and there are no pending jobs
@@ -352,15 +339,16 @@ mysql nextcloud <<<"UPDATE oc_jobs SET reserved_at=0;"
 
 # cleanup
 ####################
-cleanup() {
-  local RET=$?
+function cleanup
+{
+  local RET="$?"
   set +eE
   echo "Clean up..."
   rm -rf "$BASEDIR"/nextcloud.tar.bz2 "$BASEDIR"/nextcloud-old
   trap "" EXIT
-  exit $RET
+  exit "$RET"
 }
-trap cleanup EXIT
+trap 'cleanup' EXIT SIGHUP SIGILL SIGABRT SIGINT
 
 # get new code
 ####################
@@ -378,7 +366,7 @@ LIMIT=0
 echo "Back up current instance..."
 set +eE
 ncp-backup "$BKPDIR" "$WITH_DATA" "$COMPRESSED" "$LIMIT" # && false # test point
-RET=$?
+RET="$?"
 sync
 set -eE
 
