࿓❯ Update
Signed-off-by: Victor-ray, S <12261439+ZendaiOwl@users.noreply.github.com>

diff --git a/bin/ncp-update b/bin/ncp-update
--- a/bin/ncp-update
+++ b/bin/ncp-update
@@ -17,7 +17,7 @@ function log
       case "$LOGLEVEL" in
         -2)
            local -r CYAN='\e[1;36m'
-           printf "${CYAN}DEBUG${Z} %s\n" "$TEXT"
+           printf "${CYAN}DEBUG${Z} %s\n" "$TEXT" >&2
            ;;
         -1)
            local -r BLUE='\e[1;34m'
@@ -33,11 +33,37 @@ function log
            ;;
          2)
            local -r RED='\e[1;31m'
-           printf "${RED}ERROR${Z} %s\n" "$TEXT"
+           printf "${RED}ERROR${Z} %s\n" "$TEXT" >&2
            ;;
       esac
     else
       log 2 "Invalid log level: [Debug: -2|Info: -1|Success: 0|Warning: 1|Error: 2]"
+    fi
+  fi
+}
+
+function remove_tmp_directory
+{
+  if ! rm --recursive --force "$TMPDIR"; then
+    log 2 "Failed to remove directory: $TMPDIR"
+    return 1
+  else
+    log 0 "Removed tmp directory: $TMPDIR"
+    return 0
+  fi
+}
+
+function clean_ncp_update
+{
+  if ! cd /; then
+    log 2 "Failed to change directory to: /"
+    log -1 "Attempting to remove tmp directory nonetheless"
+    if ! remove_tmp_directory; then
+      exit 1
+    fi
+  else
+    if ! remove_tmp_directory; then
+      exit 1
     fi
   fi
 }
@@ -54,7 +80,10 @@ If you are sure that you know what you are doing, you can still execute the upda
 fi
 
 {
-  [ "$(id -u)" -ne 0 ] && { log 2 "Must be run as root. Try 'sudo $0'"; exit 1; }
+  if [[ "$(id -u)" -ne 0 ]]; then
+    log 2 "Must be run as root or with sudo. Try 'sudo ${BASH_SOURCE[0]}'"
+    exit 1
+  fi
 
   #OWNER="${OWNER:-nextcloud}"
   OWNER="${OWNER:-ZendaiOwl}"
@@ -62,10 +91,10 @@ fi
   BRANCH="${1:-master}"
   [[ "$BRANCH" != "master" ]] && log -1 "Updating to development branch: $BRANCH"
 
-  TMPDIR="$( mktemp -d /tmp/ncp-update.XXXXXX || ( echo "Failed to create temp dir. Exiting" >&2; exit 1 ) )"
-  trap 'cd /; rm -rf "$TMPDIR"' EXIT
+  TMPDIR="$( mktemp -d /tmp/ncp-update.XXXXXX || ({ log 2 "Failed to create temp dir. Exiting"; exit 1 }) )"
+  trap 'clean_ncp_update' EXIT SIGHUP SIGILL SIGABRT SIGINT
 
-  echo -e "Downloading updates"
+  log -1 "Downloading updates"
   git clone --depth 20 -b "$BRANCH" -q https://github.com/"$OWNER"/"$REPO".git "$TMPDIR" || {
     log 2 "No internet connectivity"
     exit 1
@@ -73,7 +102,11 @@ fi
 
   # shellcheck disable=SC2164
   [[ -f /.ncp-image ]] || {
-    cd "$TMPDIR"         # update locally during build
+    # Update locally during build
+    if ! cd "$TMPDIR"; then
+      log 2 "Failed to change directory to: $TMPDIR"
+      exit 1
+    fi
 
     [[ -z "$2" ]] || {
       git fetch origin "$2" || {
