࿓❯ Update
Signed-off-by: Victor-ray, S <12261439+ZendaiOwl@users.noreply.github.com>

diff --git a/bin/ncp-update-nc b/bin/ncp-update-nc
--- a/bin/ncp-update-nc
+++ b/bin/ncp-update-nc
@@ -36,11 +36,8 @@ function isRoot
 function isUser
 {
   [[ "$#" -ne 1 ]] && return 2
-  if id -u "$1" &>/dev/null; then
-    return 0
-  else
-    return 1
-  fi
+  if id -u "$1" &>/dev/null; then return 0
+  else return 1; fi
 }
 
 # Checks if a given path to a file exists
@@ -276,24 +273,18 @@ BIN="${0##*/}"
 
 # shellcheck disable=SC1090
 if isFile '/usr/local/etc/library.sh'; then source '/usr/local/etc/library.sh'
-elif isFile 'etc/library.sh'; then source '/usr/local/etc/library.sh'
-fi
+elif isFile 'etc/library.sh'; then source '/usr/local/etc/library.sh'; fi
 
 # pre-checks
 ####################
-if isZero "$VER"; then log 2 "Usage: $BIN <version>"; exit 1
-fi
+if isZero "$VER"; then log 2 "Usage: $BIN <version>"; exit 1; fi
 
 if isFile '/.docker-image'; then BASEDIR='/data'
-else BASEDIR='/var/www'
-fi
+else BASEDIR='/var/www'; fi
 
 log -2 "BASEDIR: $BASEDIR"
 
-if ! cd "$BASEDIR"; then
-  log 2 "Failed to change directory to: $BASEDIR"
-  exit 1
-fi
+if ! cd "$BASEDIR"; then log 2 "Failed to change directory to: $BASEDIR"; exit 1; fi
 
 DATADIR="$( get_nc_config_value datadirectory )"
 ncc status &>/dev/null          || { [[ "$DBG" == x ]] && ncc status; echo "Nextcloud is currently down"; exit 1; }
@@ -304,8 +295,7 @@ ncc status &>/dev/null          || { [[ "$DBG" == x ]] && ncc status; echo "Next
 # check version
 ####################
 
-if isRoot; then SUDO=(sudo -u www-data)
-fi
+if isRoot; then SUDO=(sudo -u www-data); fi
 
 CURRENT="$( "${SUDO[@]}" php /var/www/nextcloud/occ status | grep "version:" | awk '{ print $3 }' )"
 MAJOR_CUR="$( cut -d. -f1 <<<"$CURRENT" )"
@@ -322,8 +312,7 @@ fi
 grep -qP "\d+\.\d+\.\d+" <<<"$CURRENT" || { echo "Malformed version $CURRENT"; exit 1; }
 grep -qP "\d+\.\d+\.\d+" <<<"$VER"     || { echo "Malformed version $VER"    ; exit 1; }
 
-log -1 "Current Nextcloud version: $CURRENT"
-log -1 "Available Nextcloud version: $VER"
+log -1 "Current Nextcloud version: $CURRENT"; log -1 "Available Nextcloud version: $VER"
 is_more_recent_than "$VER" "$CURRENT" || { log -1 "Nothing to update"; exit 1; } # we want `exit 1` so the autoupdate doesn't notify success in this case
 
 
@@ -343,11 +332,12 @@ function cleanup
 {
   local RET="$?"
   set +eE
-  echo "Clean up..."
+  echo "Cleanup"
   rm -rf "$BASEDIR"/nextcloud.tar.bz2 "$BASEDIR"/nextcloud-old
   trap "" EXIT
   exit "$RET"
 }
+
 trap 'cleanup' EXIT SIGHUP SIGILL SIGABRT SIGINT
 
 # get new code
@@ -372,7 +362,7 @@ set -eE
 
 BKP_="$( ls -1t "$BKPDIR"/nextcloud-bkp_*.tar.gz 2>/dev/null | head -1 )"
 [[ -f "$BKP_"  ]] || {                set +eE; echo "Error backing up"; false || cleanup; }
-[[ $RET -ne 0  ]] && { rm -f "$BKP_"; set +eE; echo "Error backing up"; false || cleanup; }
+[[ "$RET" -ne 0  ]] && { rm -f "$BKP_"; set +eE; echo "Error backing up"; false || cleanup; }
 BKP="$( dirname "$BKP_" )/$( basename "$BKP_" .tar.gz )-${CURRENT}.tar.gz"
 echo "Storing backup at '$BKP'..."
 mv "$BKP_" "$BKP"
@@ -383,11 +373,12 @@ rollback_simple() {
   set +eE
   trap "" INT TERM HUP ERR
   echo -e "Abort\nSimple roll back..."
-  rm -rf "$BASEDIR"/nextcloud
+  rm --recursive --force "$BASEDIR"/nextcloud
   mv "$BASEDIR"/nextcloud-old "$BASEDIR"/nextcloud
   false || cleanup                 # so cleanup exits with 1
 }
-trap rollback_simple INT TERM HUP ERR
+
+trap 'rollback_simple' INT TERM HUP ERR
 
 # replace code
 ####################
@@ -407,17 +398,14 @@ cp -raT nextcloud-old/themes/ nextcloud/themes/
 # copy old NCP apps
 ####################
 for app in nextcloudpi previewgenerator; do
-  if [[ -d nextcloud-old/apps/"${app}" ]]; then
-    cp -r -L nextcloud-old/apps/"${app}" /var/www/nextcloud/apps/
-  fi
+  if [[ -d nextcloud-old/apps/"${app}" ]]; then cp -r -L nextcloud-old/apps/"${app}" /var/www/nextcloud/apps/; fi
 done
 
 #false # test point
 
 # copy data if it was at the default location
 ####################
-if [[ "$DATADIR" == "/var/www/nextcloud/data" ]] || [[ "$DATADIR" == "/data/nextcloud/data" ]]; then
-  echo "Restore data..."
+if [[ "$DATADIR" == "/var/www/nextcloud/data" ]] || [[ "$DATADIR" == "/data/nextcloud/data" ]]; then echo "Restore data..."
   mv -T nextcloud-old/data nextcloud/data
 fi
 
@@ -435,9 +423,7 @@ rollback() {
   [[ "$DATADIR" == "$BASEDIR/nextcloud/data" ]] && mv -T "$DATADIR" "$TMPDATA"
   ncp-restore "$BKP" || { echo "Rollback failed! Data left at $TMPDATA"; exit 1; }
   [[ "$DATADIR" == "$BASEDIR/nextcloud/data" ]] && { rm -rf "$DATADIR"; mv -T "$TMPDATA" "$DATADIR"; }
-  rm "$BKP"
-  echo "Rollback successful. Nothing was updated"
-  exit 1
+  rm "$BKP"; echo "Rollback successful. Nothing was updated"; exit 1
 }
 trap rollback INT TERM HUP ERR
 
@@ -460,8 +446,7 @@ $ncc | grep -q db:convert-filecache-bigint && $ncc db:convert-filecache-bigint -
 
 # use the correct version for custom apps
 NCVER="$(ncc status | grep "version:" | awk '{ print $3 }')"
-if is_more_recent_than "21.0.0" "${NCVER}"; then
-  NCPREV=/var/www/ncp-previewgenerator/ncp-previewgenerator-nc20
+if is_more_recent_than "21.0.0" "${NCVER}"; then NCPREV=/var/www/ncp-previewgenerator/ncp-previewgenerator-nc20
 else
   # Install notify_push if not installed
   if ! is_app_enabled notify_push; then
@@ -487,75 +472,73 @@ fi
 rm -rf /var/www/nextcloud/apps/previewgenerator
 ln -snf "${NCPREV}" /var/www/nextcloud/apps/previewgenerator
 
-if ! is_docker && ! is_more_recent_than "24.0.0" "${NCVER}" && is_more_recent_than "8.1.0" "${PHPVER}.0"
-then
+if ! is_docker && ! is_more_recent_than "24.0.0" "${NCVER}" && is_more_recent_than "8.1.0" "${PHPVER}.0"; then
   (
-  echo "Upgrading PHP..."
-  export DEBIAN_FRONTEND=noninteractive
-  PHPVER_OLD="$PHPVER"
-  PHPVER_NEW="8.1"
-  PHP_PACKAGES_OLD=(php-{common,igbinary,redis,json} "php${PHPVER_OLD}" \
-    "php${PHPVER_OLD}"-{curl,gd,fpm,cli,opcache,mbstring,xml,zip,fileinfo,ldap,intl,bz2,json,common,readline,mysql,bcmath,gmp})
-  PHP_PACKAGES_NEW=("php${PHPVER_NEW}" \
-    "php${PHPVER_NEW}"-{curl,gd,fpm,cli,opcache,mbstring,xml,zip,fileinfo,ldap,intl,bz2,mysql,bcmath,gmp,redis,common})
-
-  php_restore() {
-    trap "" INT TERM HUP ERR
-    echo "Something went wrong while upgrading PHP. Rolling back to version ${PHPVER_OLD}..."
-    set +e
-    service "php${PHPVER_NEW}-fpm" stop
-    a2disconf php${PHPVER_NEW}-fpm
-    rm /etc/apt/sources.list.d/php.list
+    echo "Upgrading PHP..."
+    export DEBIAN_FRONTEND=noninteractive
+    PHPVER_OLD="$PHPVER"
+    PHPVER_NEW="8.1"
+    PHP_PACKAGES_OLD=(php-{common,igbinary,redis,json} "php${PHPVER_OLD}" \
+      "php${PHPVER_OLD}"-{curl,gd,fpm,cli,opcache,mbstring,xml,zip,fileinfo,ldap,intl,bz2,json,common,readline,mysql,bcmath,gmp})
+    PHP_PACKAGES_NEW=("php${PHPVER_NEW}" \
+      "php${PHPVER_NEW}"-{curl,gd,fpm,cli,opcache,mbstring,xml,zip,fileinfo,ldap,intl,bz2,mysql,bcmath,gmp,redis,common})
+    
+    function php_restore
+    {
+      trap "" INT TERM HUP ERR
+      echo "Something went wrong while upgrading PHP. Rolling back to version ${PHPVER_OLD}..."
+      set +e
+      service "php${PHPVER_NEW}-fpm" stop
+      a2disconf php"$PHPVER_NEW"-fpm
+      rm /etc/apt/sources.list.d/php.list
+      apt-get update
+      apt-get remove --purge -y "${PHP_PACKAGES_NEW[@]}"
+      apt-get install -y --no-install-recommends -t "$RELEASE" "${PHP_PACKAGES_OLD[@]}"
+      set_ncpcfg "php_version" "$PHPVER_OLD"
+      install_template "php/opcache.ini.sh" "/etc/php/${PHPVER_NEW}/mods-available/opcache.ini"
+      run_app nc-limits
+      a2enconf "php${PHPVER_OLD}-fpm"
+      service "php${PHPVER_OLD}-fpm" start
+      service apache2 restart
+      echo "PHP upgrade has been successfully reverted"
+      set -e
+    }
+    
+    trap php_restore INT TERM HUP ERR
+    
+    # Setup apt repository for php 8
+    wget -O /etc/apt/trusted.gpg.d/php.gpg https://packages.sury.org/php/apt.gpg
+    echo "deb https://packages.sury.org/php/ ${RELEASE%-security} main" > /etc/apt/sources.list.d/php.list
     apt-get update
-    apt-get remove --purge -y "${PHP_PACKAGES_NEW[@]}"
-    apt-get install -y --no-install-recommends -t "$RELEASE" "${PHP_PACKAGES_OLD[@]}"
-    set_ncpcfg "php_version" "${PHPVER_OLD}"
+    
+    clear_opcache
+    
+    echo "Stopping apache and php-fpm..."
+    service "php${PHPVER_OLD}-fpm" stop
+    service apache2 stop
+    
+    echo "Remove old PHP ($PHPVER_OLD)..."
+    a2disconf "php${PHPVER_OLD}-fpm"
+    
+    apt-get remove --purge -y "${PHP_PACKAGES_OLD[@]}"
+    
+    echo "Install PHP: $PHPVER_NEW"
+    install_with_shadow_workaround --no-install-recommends systemd
+    apt-get install -y --no-install-recommends -t "$RELEASE" "${PHP_PACKAGES_NEW[@]}"
+    
+    set_ncpcfg "php_version" "${PHPVER_NEW}"
     install_template "php/opcache.ini.sh" "/etc/php/${PHPVER_NEW}/mods-available/opcache.ini"
-    run_app nc-limits
-    a2enconf "php${PHPVER_OLD}-fpm"
-    service "php${PHPVER_OLD}-fpm" start
-    service apache2 restart
-    echo "PHP upgrade has been successfully reverted"
-    set -e
-  }
-
-  trap php_restore INT TERM HUP ERR
-
-  # Setup apt repository for php 8
-  wget -O /etc/apt/trusted.gpg.d/php.gpg https://packages.sury.org/php/apt.gpg
-  echo "deb https://packages.sury.org/php/ ${RELEASE%-security} main" > /etc/apt/sources.list.d/php.list
-  apt-get update
-
-  clear_opcache
-
-  echo "Stopping apache and  php-fpm..."
-  service "php${PHPVER_OLD}-fpm" stop
-  service apache2 stop
-
-  echo "Remove old PHP (${PHPVER_OLD})..."
-  a2disconf "php${PHPVER_OLD}-fpm"
-
-  apt-get remove --purge -y "${PHP_PACKAGES_OLD[@]}"
-
-  echo "Install PHP ${PHPVER_NEW}..."
-  install_with_shadow_workaround --no-install-recommends systemd
-  apt-get install -y --no-install-recommends -t "$RELEASE" "${PHP_PACKAGES_NEW[@]}"
-
-  set_ncpcfg "php_version" "${PHPVER_NEW}"
-  install_template "php/opcache.ini.sh" "/etc/php/${PHPVER_NEW}/mods-available/opcache.ini"
-  ( set -e; export PHPVER="${PHPVER_NEW}"; run_app nc-limits )
-
-  a2enconf "php${PHPVER_NEW}-fpm"
-
-  echo "Starting apache and php-fpm..."
-  service "php${PHPVER_NEW}-fpm" start
-  service apache2 start
-  ncc status
+    ( set -e; export PHPVER="${PHPVER_NEW}"; run_app nc-limits )
+    
+    a2enconf "php${PHPVER_NEW}-fpm"
+    
+    echo "Starting apache and php-fpm..."
+    service "php${PHPVER_NEW}-fpm" start
+    service apache2 start
+    ncc status
   )
-
   # Reload library.sh to reset PHPVER
   source /usr/local/etc/library.sh
-
 fi
 
 # refresh completions
@@ -563,6 +546,7 @@ ncc _completion -g --shell-type bash -p ncc | sed 's|/var/www/nextcloud/occ|ncc|
 
 echo "Update completed successfully."
 # done
+
 ####################
 mkdir -p  "$DATADIR"/ncp-update-backups
 mv "$BKP" "$DATADIR"/ncp-update-backups
